name: CI
on: [push, pull_request]
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21
          cache: maven
      - name: Maven Build
        run: mvn clean package -DskipTests
      - uses: actions/upload-artifact@v4
        with:
          name: target
          path: target/
          retention-days: 1

  integration-test:
    name: Integration Test (DB API ${{ matrix.db-api-version }}.x.x)
    needs: build
    runs-on: ubuntu-latest
    env:
      CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
    strategy:
      fail-fast: false
      matrix:
        db-api-version: [6, 7]
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21
          cache: maven
      - uses: actions/download-artifact@v4
        with:
          name: target
      - name: Maven Integration Test
        run: mvn verify -Dgpg.skip -P docker-integration-test-db-api-${{ matrix.db-api-version }},cypress-with-recording-db-api-${{ matrix.db-api-version }}
